siteTitle = "cncjs"
baseColor = "#222"
linkPrefix = ""
docPages = [
    "/docs/",
    "/docs/installation/",
    "/docs/rpi-setup-guide/",
    "/docs/desktop-app/",
    "/docs/user-guide/",
    "/docs/troubleshooting/",
    "/docs/faq/",
    "/docs/resources/",
    "/docs/shapeoko/",
    "/docs/about/"
]
